### ISSUE TITLE
the rules about the environment

### ISSUE THREAD

**Issue by lyhlyhl** [vwxyzjn/gym-microrts#40]
I have read the paper your readme.md mentioned. I think the game is similar to the StarCraft II ，but it is simpler than StarCraft II. So, is there any papers or introductions about the rules of the game? it will help me to try my agent. It is more than appreciative.

**Comment by vwxyzjn** [comment]
Hey, we have documentation here: https://github.com/santiontanon/microrts/wiki/Game-Definition

**Comment by lyhlyhl** [comment]
wow，thanks a lot !

**Comment by vwxyzjn** [comment]
Closing this issue now, but feel free to re open if you have further questions.
