### ISSUE TITLE
Saving and loading model

### ISSUE THREAD

**Issue by ianyou0317** [vwxyzjn/gym-microrts#5]
Hi @vwxyzjn ,I really appreciate for this wonderful MicroRTS gym wrapper. The project works very well, but I wonder how to save the well-trained model and loading to others environments. Thanks in advance.

**Comment by vwxyzjn** [comment]
In pytorch, saving models is trivially easy. See https://pytorch.org/tutorials/beginner/saving_loading_models.html.

All you have to do is 

```
torch.save(agent.state_dict(), PATH)

#load
agent = Agent()
agent.load_state_dict(torch.load(PATH))
agent.eval()
```

**Comment by vwxyzjn** [comment]
Closing this issue for now. Let me know if you have additional questions :)
