### ISSUE TITLE
Adjust reward

### ISSUE THREAD

**Issue by Nico1ee** [vwxyzjn/gym-microrts#7]
Hi @vwxyzjn , thanks for providing this wrappers.
I want to let agent collect resources at the beginning, then produce workers, and finally attack enemy to win the game.
In ppo algorithm, how to adjust the rewards gradually according to the time of each game(episode_steps) ?

**Comment by vwxyzjn** [comment]
See below as an example on how to shape the rewards

https://github.com/vwxyzjn/gym-microrts/blob/7ac6f8ad0c6f4bd51836228c9951fa68756710c4/gym_microrts/v1.py#L174
https://github.com/vwxyzjn/gym-microrts/blob/7ac6f8ad0c6f4bd51836228c9951fa68756710c4/gym_microrts/envs/global_agent_env.py#L160

Our ppo implmentation is able to learn this behavior (https://streamable.com/o797ca) in `MicrortsRandomEnemyShapedReward3-v1`

**Comment by Nico1ee** [comment]
Thanks for your reply.
I tried to train a agent with ppo algorithm using the instructions you provided, but the agent usually loses to randomAI.
Through observation, I found that the agent works well at the beginning of the game. It will collects, produce workers, and attacks the enemy’s base. 
However, as the game time passes, agent won't attack enemy just stay near our base. It's looks like waiting to die, let us lose the game.


I have a few doubts:
1. Because the location of the base is fixed during training, agent only learns to attack the enemy's base.
2. Reward should consider time penalty.
3. Avoid agents using invalid commands to control game characters.

Please give me some help, Thank you.

**Comment by vwxyzjn** [comment]
Hi, sorry for the delay in reply. In general reward shaping is kind of brittle. Agents by chance discover diverse set of policies. Feel free to play with the reward shaping weights here https://github.com/vwxyzjn/gym-microrts/blob/7ac6f8ad0c6f4bd51836228c9951fa68756710c4/gym_microrts/v1.py#L174

**Comment by vwxyzjn** [comment]
Closing the issue but feel free to open another one should you have new questions. Thanks for reporting this issue.
