### ISSUE TITLE
Cannot import 'JNIGridnetVecClient' from ts

### ISSUE THREAD

**Issue by chloebeth** [vwxyzjn/gym-microrts#79]
Hello, I am opening this in case someone else has ran into this same issues. I am attempting to run hello_world.py, pop_gridnet_eval.py, etc on a MacOS  and I am getting this error. I am hoping someone else has ran into this issue before. Thank you so much for your time!

**Comment by vwxyzjn** [comment]
https://github.com/vwxyzjn/gym-microrts/issues/12#issuecomment-879058480 Please recursively clone git repo

**Comment by chloebeth** [comment]
Hi, I tried this and I am still unable to run hello_world.py or pop_gridnet_eval.py. I have traced the error back to JNIGridnetVecClient.java with client initialization.

**Comment by vwxyzjn** [comment]
Do you have JAVA installed? Inspect `build.log` for further detail

**Comment by vwxyzjn** [comment]
Try pulling the master for better error messages. CC #80

**Comment by chloebeth** [comment]
Yes I have java and the build is clean

**Comment by vwxyzjn** [comment]
Could you check if there is a `microrts.jar` being built in `gym_microrts/microrts/` folder?

**Comment by chloebeth** [comment]
hi, yes there was. i switched to an ubuntu vm and everything  works. I guess for some reason it does not run on macos

**Comment by vwxyzjn** [comment]
Great thanks. It should till work on Mac OS but render would not work.
